---
# ------------------------------------------------------------------------
# tasks file for update
# ------------------------------------------------------------------------

- name: install update
  package:
    name: "{{ update_packages }}"
    state: present
  register: update_install_update
  until: update_install_update is succeeded
  retries: 3

- name: configure update
  template:
    src: "{{ update_config_file }}.j2"
    dest: "{{ update_config_directory }}/{{ update_config_file }}"
  notify:
    - restart update

- name: start and enable update
  service:
    name: "{{ update_service }}"
    state: started
    enabled: true
  when:
    - ansible_virtualization_type != "docker"
